## **02 - Matrix Operations in Numpy**

In this notebook, we will explore how to perform basic and advanced matrix operations using NumPy. Matrices are a fundamental part of data manipulation, machine learning, and linear algebra.

### **1\. Creating Matrices**

A matrix in NumPy is simply a 2D array.

#### **Examples:**

In [ ]:
%pip install numpy

In [ ]:
import numpy as np

# Creating a matrix
matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix A:\n", matrix_a)

# Creating a matrix of zeros
zeros_matrix = np.zeros((3, 3))
print("Zeros Matrix:\n", zeros_matrix)

# Creating a matrix of ones
ones_matrix = np.ones((2, 4))
print("Ones Matrix:\n", ones_matrix)

# Creating an identity matrix
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)

### **2\. Basic Matrix Operations**

#### **Addition and Subtraction**

In [ ]:
matrix_b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Matrix addition
result_add = matrix_a + matrix_b
print("Matrix Addition:\n", result_add)

# Matrix subtraction
result_sub = matrix_a - matrix_b
print("Matrix Subtraction:\n", result_sub)

 **Element-wise Multiplication**

In [8]:
result_mul = matrix_a * matrix_b

print("Element-wise Multiplication:\n", result_mul)

Element-wise Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


### **3\. Matrix Multiplication**

#### **Dot Product**
Matrix multiplication involves the dot product of rows and columns.

In [ ]:
result_dot = np.dot(matrix_a,matrix_b)
print("Matrix Multiplication (Dot Product):\n", result_dot)

#### **@ Operator (Preferred for Matrix Multiplication)**

In [7]:
# Using @ operator for matrix multiplication
result_at = matrix_a @ matrix_b
print("Matrix Multiplication (@ Operator):\n", result_at)

Matrix Multiplication (@ Operator):
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


### **4\. Transpose of a Matrix**

The transpose of a matrix flips it over its diagonal, interchanging rows and columns.

In [ ]:
# Transpose of a matrix
transpose_a = matrix_a.T
print("Transpose of Matrix A:\n", transpose_a)

### **5\. Determinant of a Matrix**

The determinant is a scalar value that can be computed from the elements of a square matrix.

In [ ]:
from numpy.linalg import det

# Determinant of a matrix
det_a = det(matrix_a)
print("Determinant of Matrix A:", det_a)

### **6\. Inverse of a Matrix**

The inverse of a matrix exists only for square matrices with a non-zero determinant.

In [ ]:
from numpy.linalg import inv

# Inverse of a matrix
matrix_c = np.array([[4, 7], [2, 6]])
inverse_c = inv(matrix_c)
print("Matrix C:\n", matrix_c)
print("Inverse of Matrix C:\n", inverse_c)

### **7\. Eigenvalues and Eigenvectors**

Eigenvalues and eigenvectors are fundamental concepts in linear algebra.

In [ ]:
from numpy.linalg import eig

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = eig(matrix_a)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

### **7\. Eigenvalues and Eigenvectors**

Eigenvalues and eigenvectors are fundamental concepts in linear algebra.

In [ ]:
from numpy.linalg import solve

# Coefficient matrix (A)
A = np.array([[3, 1], [1, 2]])

# Constant matrix (B)
B = np.array([9, 8])

# Solving for X
X = solve(A, B)
print("Solution X:", X)

### **8\. Solving a System of Linear Equations**

You can solve equations of the form AX=BAX = BAX=B where AAA is a matrix, BBB is a vector, and XXX is the unknown.

In [ ]:
from numpy.linalg import solve

# Coefficient matrix (A)
A = np.array([[3, 1], [1, 2]])

# Constant matrix (B)
B = np.array([9, 8])

# Solving for X
X = solve(A, B)
print("Solution X:", X)

### **9\. Other Useful Linear Algebra Functions**

*   **Matrix Rank**: Determines the rank of a matrix.
*   **Trace**: Sum of diagonal elements.

In [18]:
# Example data
X = np.array([[1, 1], [1, 2], [1, 3]])
y = np.array([1, 2, 3])

# Normal equation
theta = inv(X.T @ X) @ X.T @ y
print("Coefficients (theta):", theta)

Coefficients (theta): [-1.77635684e-15  1.00000000e+00]
